# Generated by Django 6.0 on 2026-01-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('experience_years', models.PositiveIntegerField()),
                ('skills', models.CharField(max_length=255)),
                ('telegram', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
